add backtracking line search
mayataka/robotoc pull request #72
Opened 2021-10-24 05:13 UTC by z8674558

https://github.com/mayataka/idocp/issues/55

hi @mayataka, this is my attempt to add backtracking line search based on my understandings below:

- KKT residuals are the gradients for the objective function and the constraint violations. Thus, we can get a directional derivative by computing a dot product of the residual and the direction.
- In `SplitOCP`,  the directional derivative is `lx・dx + la・da + lu・du + lf・df`. It is `lx・dx` in `TerminalOCP` and `lx・dx + ldv・ddv + lf・df` in `ImpulseSplitOCP`.
- For a problem with multiple time stages, we will accept the step size if the sum of lhs values in the Armijo conditions for each stages are smaller than the sum of rhs values.

Could you check if I am in the right direction?

2021-10-30 13:28 UTC, mayataka commented
Thank you very much @z8674558. 
The computation of the penalty parameter and the merit function sounds really nice.
One remaining consideration is how to compute the directional derivative of the merit function.
One possible approach is to use the finite difference:
Consider a small difference, e.g., eps = 1.0e-08, and approximate the directional derivative as 
```
directional_derivative =  (1.0 / eps) * (merit_fun(max_step_size+eps) - merit_fun(max_step_size))
```
where max_step_size is the maximum step size computed by RiccatiRecursion::maxPrimalStepSize().

2021-10-30 14:33 UTC, z8674558 commented
thank you @mayataka, will work on.

weird, ctest is failing on CI despite the fact that it passes on my local environment with a release build.

2021-10-30 23:46 UTC, mayataka commented
I have seen the error of the test.
It may be due to some matrix-matrix multiplication or dot products failing because the dimensions are not consistent.

2021-10-31 01:47 UTC, mayataka commented
The last consideration is how to switch the merit-backtracking line search and filter line search.
For example, in Ipopt, a switching condition is used to determine which method to use.
(equation (19) of http://cepac.cheme.cmu.edu/pasilectures/biegler/ipopt.pdf)
It may be reasonable, but the implementation can be really complicated.
Another possibility is that the user chooses which one to use.
For example, change the solution update as
```
void OCPSolver::updateSolution(const double t, const Eigen::VectorXd& q, 
                                                     const Eigen::VectorXd& v, const bool line_search=false,
                                                     const std::string& line_search_method="filter");
```

2021-11-01 13:58 UTC, mayataka commented
@z8674558 
Thank you very much, the commits are excellent!
I have left several comments.
Could you check them and modify some code?
After that, I'll merge this pull request.

2021-11-01 15:09 UTC, z8674558 commented
@mayataka maybe you forgot to submit review comments?

2021-11-01 22:14 UTC, mayataka requested changes

2021-11-01 22:24 UTC, mayataka commented
@z8674558 
You are right.

2021-11-02 01:42 UTC, mayataka commented on include/robotoc/impulse/impulse_split_solution.hxx
> +  for (int i=0; i<f.size(); ++i) {
Or simply you can extract the stack of the Lagrange multipliers for the active constraints as 
```
double mu_linf = 0;
if (has_active_contacts_) {
  const double linf = mu_stack().array().abs().maxCoeff();
  mu_linf = ((mu_linf < linf) ? linf : mu_linf);
}
```

2021-11-02 01:43 UTC, mayataka commented on include/robotoc/ocp/split_solution.hxx
> +  double mu_linf = 0;
Or simply you can extract the stack of the Lagrange multipliers for the active constraints as 
```
double mu_linf = 0;
if (dimi_ > 0) {
  const double linf = mu_stack().array().abs().maxCoeff();
  mu_linf = ((mu_linf < linf) ? linf : mu_linf);
}
```

2021-11-02 03:47 UTC, mayataka commented on src/line_search/line_search.cpp
> +  const double eps = 1.0e-08;
This `eps` should be included in `LineSearchSettings`.

2021-11-02 09:56 UTC, mayataka commented on include/robotoc/ocp/split_solution.hxx
> +  }
For example, you can write this as 
```
double xi_linf = 0;
if (dimi_ > 0) {
  const double linf = xi_stack().array().abs().maxCoeff();
  xi_linf = ((xi_linf < linf) ? linf : xi_linf);
}
```

2021-11-02 11:25 UTC, z8674558 commented on src/solver/ocp_solver.cpp
> + void OCPSolver::setLineSearchSettings(const LineSearchSettings& settings) {
It is already there? https://github.com/z8674558/idocp/blob/62b39001211fba9aed957cac1f54d4dc63439d11/include/robotoc/solver/ocp_solver.hpp#L210

2021-11-02 12:00 UTC, mayataka commented on src/solver/ocp_solver.cpp
> + void OCPSolver::setLineSearchSettings(const LineSearchSettings& settings) {
Sorry, I missed it.

2021-11-02 12:03 UTC, mayataka approved these changes
@z8674558 
The all the changes are perfect!
I'll merge as soon as the CI is passed.

2021-11-02 12:04 UTC, z8674558 commented
thank you for the continued support. 🙏🙏

2021-11-02 13:58 UTC, merged

2021-11-02 13:58 UTC, mayataka commented
@z8674558 
Thank you very much for your contribution!